version: '3'

services:
  app:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./symfony/public:/var/www/html/
      - ./symfony:/var/www/
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=your_database
      - POSTGRES_USER=your_user
      - POSTGRES_PASSWORD=your_password
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: