version: '3'

services:
  app:
    build:
      context: ./symfony
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./symfony/public:/var/www/html/
      - ./symfony:/var/www/
    command: >
      bash -c "
        echo 'Running startup tasks...' &&
        composer install &&
        php -S 0.0.0.0:80 -t ./html ./html/index.php
      "
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGPORT=${POSTGRES_PORT}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: