<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXJO8JWd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXJO8JWd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXJO8JWd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXJO8JWd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXJO8JWd\App_KernelDevDebugContainer([
    'container.build_hash' => 'XJO8JWd',
    'container.build_id' => '89d93c42',
    'container.build_time' => 1727614291,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXJO8JWd');
